### ISSUE TITLE
java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while loading gnu.io.RXTXCommDriver

### ISSUE THREAD

**Issue by pneumaticdeath** [chipKIT32/chipKIT32-MAX#41]
While trying to start the IDE on stock(is) ubuntu Lucid install it throws the following exception:

java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path thrown while loading gnu.io.RXTXCommDriver
Exception in thread "main" java.lang.UnsatisfiedLinkError: no rxtxSerial in java.library.path
    at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1734)
    at java.lang.Runtime.loadLibrary0(Runtime.java:823)
    at java.lang.System.loadLibrary(System.java:1028)
    at gnu.io.CommPortIdentifier.<clinit>(CommPortIdentifier.java:83)
    at processing.app.Editor.populateSerialMenu(Editor.java:967)
    at processing.app.Editor.buildToolsMenu(Editor.java:704)
    at processing.app.Editor.buildMenuBar(Editor.java:486)
    at processing.app.Editor.<init>(Editor.java:208)
    at processing.app.Base.handleOpen(Base.java:732)
    at processing.app.Base.handleOpen(Base.java:697)
    at processing.app.Base.handleNew(Base.java:594)
    at processing.app.Base.<init>(Base.java:334)
    at processing.app.Base.main(Base.java:208)

mitch@phobos:~/mpide/mpide-0022-chipkit-linux32-20110520$ uname -a
Linux phobos 2.6.32-32-generic #62-Ubuntu SMP Wed Apr 20 21:54:21 UTC 2011 i686 GNU/Linux
mitch@phobos:~/mpide/mpide-0022-chipkit-linux32-20110520$ java -version
java version "1.6.0_24"
Java(TM) SE Runtime Environment (build 1.6.0_24-b07)
Java HotSpot(TM) Client VM (build 19.1-b02, mixed mode, sharing)

**Comment by ananyuan** [comment]
java can dynamic set the System property, include java.library.path. 
there is a sample, need put the dll in the lib directory,

/**
* set java.library.path
*/
private static void setLibPath() {
 String pathSeparator = System.getProperty("path.separator");
 
 String libPath = System.getProperty("java.library.path") + pathSeparator + Context.getWEBINF() + "/lib";

 try {
  System.setProperty("java.library.path", libPath);
  Field fieldSysPath = ClassLoader.class.getDeclaredField("sys_paths");
  fieldSysPath.setAccessible(true);
  fieldSysPath.set(null, null);
  System.loadLibrary("rxtxSerial");
 } catch (Exception e) {
  log.error("set java.library.path ERROR", e);
 }
}
